### PR TITLE
Add L1TkMuon Collection in the nTuple

### PR DESCRIPTION
**Pull request by ArnabPurohit**

### CODE REVIEW

**Comment by kondratyevd** [comment]
Thanks! I will have a look.

Can you also commit whatever fixes you made to avoid filling the collections twice?
My own plotter is protected against duplicates, but it would be indeed good to have a cleaner ntupliser.

**Comment by ArnabPurohit** [comment]
> Thanks! I will have a look.
> 
> Can you also commit whatever fixes you made to avoid filling the collections twice?
> My own plotter is protected against duplicates, but it would be indeed good to have a cleaner ntupliser.

Yes, I can do that but before making further changes I think let us decide also what we want to put in our output nTuple. Because I have added few more branches and added more variables of TSOS which I do not know if we need.

**Comment by kondratyevd** [comment]
I think whatever is there is enough for now. If we decide to add more, we will do it in a another PR.

Let's try to merge this one today, just to have a working setup

**Comment by ArnabPurohit** [comment]
Updated the muonNtuples code so that there is no possibility of filling collections twice.

**Pull request merged**
